package question2;
public class TestTwo {

	    public static void main(String[] args)  {
	    	try {
	    DateAndTime d=new DateAndTime();
	    d.calc();
	    	}
	    catch(Exception m)
	    {
	    	System.out.println("Exception occured: " + m);
      	  
    	
	    }
	    
	    }

	}
